image:
  - "Visual Studio 2017"

shallow_clone: false

environment:
  CYG_BASH: "C:\\cygwin\\bin\\bash"
  CYG_CACHE: "C:\\cygwin\\var\\cache\\setup"
  CYG_MIRROR: "http://cygwin.mirror.constant.com"
  CYG_ROOT: "C:\\cygwin"
  MINGW_DIR: "C:\\msys64\\mingw64\\bin"
  Path: "C:\\Python34-x64\\;%MINGW_DIR%;%Path%"
  matrix:
    -
      BUILD_TYPE: release
      CMAKE_BUILD: cygwin
      STATIC_LIBS: true
      UNIT_TESTS: true
    -
      BUILD_TYPE: release
      CMAKE_BUILD: MSYS
      STATIC_LIBS: true
      UNIT_TESTS: true
      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;\
                 C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\ProgramFiles\\Git\\usr\\bin"
    -
      BUILD_TYPE: release
      CMAKE_BUILD: MSYS
      STATIC_LIBS: false
      UNIT_TESTS: true
      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;\
                 C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\ProgramFiles\\Git\\usr\\bin"
    -
      BUILD_TYPE: release
      CMAKE_BUILD: MinGW
      STATIC_LIBS: true
      UNIT_TESTS: true
      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;\
                 C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\ProgramFiles\\Git\\usr\\bin"
    -
      BUILD_TYPE: release
      CMAKE_BUILD: MinGW
      STATIC_LIBS: false
      UNIT_TESTS: true
      TMP_PATH: "C:\\Program Files (x86)\\CMake\\bin;C:\\Python34-x64;%MINGW_DIR%;\
                 C:\\Program Files\\Git\\cmd;C:\\msys64;C:\\ProgramFiles\\Git\\usr\\bin"

clone_folder: "C:\\projects\\NJOY2016"

before_build:
  - "set OrigPath=%Path%"
  - "set CC=%MINGW_DIR%\\gcc.exe"
  - "set CXX=%MINGW_DIR%\\g++.exe"
  - "set FC=%MINGW_DIR%\\gfortran.exe"

build_script:
  - "mkdir build"
  - "cd build"
  - "if [%CMAKE_BUILD%]==[\"cygwin\"] (
       C:\\cygwin\\setup-x86.exe -q --root %CYG_ROOT% --local-package-dir %CYG_CACHE%
       --packages cmake,make,git,python3,gcc,g++ --force-current &&
       C:\\cygwin\\bin\\bash -c cmake -D build_type=$BUILD_TYPE -D static=$STATIC_LIBS
       -D unit_tests=$UNIT_TESTS -G \"Unix Makefiles\" .. &&
       C:\\cygwin\\bin\\bash -c make -j2
     ) else (
       set Path=%TMP_PATH% &&
       cmake -D CMAKE_MAKE_PROGRAM=C:/msys64/mingw64/bin/mingw32-make.exe -D static=%STATIC_LIBS%
       -D unit_tests=%UNIT_TESTS% -G \"%CMAKE_BUILD% Makefiles\" .. &&
       set Path=%OrigPath% &&
       mingw32-make -j2
     )"

after_build:
  - "if [%CMAKE_BUILD%]==[\"cygwin\"] (
       C:\\cygwin\\bin\\bash -c \"ctest -j2 --output-on-failure\"
     ) else (
       ctest -j2 --output-on-failure
     )"
